apiVersion: v1
kind: Namespace
metadata:
  name: py2-apps
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "py2-apps"
spec:
  host: "*.py2-apps.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE

# test
