apiVersion: v1
kind: Namespace
metadata:
  name: go-apps
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "go-apps"
spec:
  host: "*.go-apps.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE