apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-go
  namespace: applications
spec:
  template:
    spec:
      containers:
        - image: docker.io/manny87/knative-helloworld:1.0
          env:
            - name: TARGET
              value: Go Sample v1
---