- name: Configure Kubeconfig 
  shell: |
    eksctl utils write-kubeconfig --name {{ cluster_name }}
  register: k8s_kubeconfig


- name: "debug msg configure kubeconfig"
  debug: 
    msg: "{{ k8s_kubeconfig }}"