- name: Configure Kubeconfig 
  shell: |
    eksctl utils write-kubeconfig --name {{ cluster_name }}
  register: k8s_kubeconfig

- name: "Debug message: Configure Kubeconfig"
  debug: 
    msg: "{{ k8s_kubeconfig }}"