- name: Create K8scluster 
  shell: |
    eksctl create cluster -f {{ eksctl_config }}
  register: k8s_eksctl_create



- name: "debug msg create eksctl cluster"
  debug: 
    msg: "{{ k8s_eksctl_create['stdout'] }}"