

# AWS

- include_tasks: assert_eksctl.yml
  when:
  - platform == "aws" 

## DEPLOY ACTIONS
- include_tasks: template_eksctl_config.yml
  when:
  - platform == "aws"
  
- include_tasks: run_ekctl_cluster_cmd.yml
  when:
  - platform == "aws"
  - action == "deploy"
  vars:
    cmdaction: create
    exclude_fail_msg: "AlreadyExistsException"

- include_tasks: configure_kubeconfig.yml
  when:
  - platform == "aws"
  - action != "delete"

## DELETE ACTIONS

- include_tasks: run_ekctl_cluster_cmd.yml
  when:
  - platform == "aws"
  - action == "delete"
  vars:
    cmdaction: delete
    exclude_fail_msg: "a" # TODO: PLACE HOLDER TILL I TEST