

# AWS

- name: Creates Outputs directory
  file:
    path: "{{role_path}}/.generated"
    state: directory
    force: true
  when:
  - action == "deploy"

- name: Tmp directory for execution
  set_fact:
    tmp_dir: "{{role_path}}/.generated"
    
- include_tasks: ../../common/tasks/assert_cli.yml
  with_items:
  - eksctl

## DEPLOY ACTIONS
- include_tasks: template_eksctl_config.yml
  when:
  - platform == "aws"
  
- include_tasks: create_eksctl_cluster.yml
  when:
  - platform == "aws"
  - action == "deploy"

- include_tasks: configure_kubeconfig.yml
  when:
  - platform == "aws"
  - action != "delete"

## DELETE ACTIONS

- include_tasks: delete_eksctl_cluster.yml
  when:
  - platform == "aws"
  - action == "delete"