
- name: Set eksctl config
  set_fact:
   eksctl_config: "{{tmp_dir}}/{{cluster_name}}.yaml"

- name: Template Generate eksctl Config 
  template:
    src: "{{ role_path }}/templates/{{ platform }}/{{provider}}/cluster.yaml.j2"
    dest: "{{ eksctl_config }}"