
- name: Creates Outputs directory
  file:
    path: "{{role_path}}/.generated"
    state: directory
    force: true

- name: Set eksctl config
  set_fact:
   eksctl_config: "{{role_path}}/.generated/{{cluster_name}}.yaml"

- name: Template Eksctl config 
  template:
    src: "{{ role_path }}/templates/{{ platform }}/{{provider}}/cluster.yaml.j2"
    dest: "{{ eksctl_config }}"
