  - name: Make sure we have a 'wheel' group
    group:
      name: wheel
      state: present
  
  - name: Allow 'wheel' group to have passwordless sudo
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'

  - name: Create a login user
    user:
      name: manny
      password: "{{ manny_pass }}"
      groups: 
      - root
      - wheel
      state: present
      shell: /bin/bash       # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/manny

  - name: Creates Certs directory
    file:
      path: "{{ certs_dir }}/"
      state: directory
      mode: u=rwX,g=rX,o=rX
      group: manny
      owner: manny
      recurse: yes