apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: testsinks.sources.manny.dev
spec:
  group: sources.manny.dev
  names:
    kind: TestSink
    plural: testsinks
  scope: Namespaced
  version: "v1alpha1"
---
apiVersion: sources.manny.dev/v1alpha1
kind: TestSink
metadata:
  name: foosink
  namespace: default
status:
  address:
    hostname: "example.com"