- hosts:  k8s1-master[0]
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: k8s1-worker
  vars_files:
    - vars.yaml
  tasks:
    - name: join cluster
      shell: "{{ hostvars[groups['k8s1-master'][0]]['join_command'] }} --ignore-preflight-errors all  >> node_joined.txt" # TODO: Remove hardcode
      args:
        chdir: $HOME
        creates: node_joined.txt