- hosts:  localhost
  gather_facts: false
  vars_files:
    - vars.yaml
  tasks:
  - name: install knative serving
    command: kubectl --kubeconfig={{ playbook_dir }}/adm.kubeconfig apply -f {{ item }}
    loop:
    - https://github.com/knative/serving/releases/download/{{ knative_serving_version }}/serving-crds.yaml
    - https://github.com/knative/serving/releases/download/{{ knative_serving_version }}/serving-core.yaml
    