#apiVersion: v1
#kind: Namespace
#metadata:
#  name: knative-samples
#---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-tcp
  namespace: knative-samples
  # labels:
  #   serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: docker.io/manny87/knative-tcp-server:1.5
          ports:
            - name: h2c
              containerPort: 4242
              protocol: TCP
---