# Generate wil helm
- name: Set Istio Init deployment file output
  set_fact:
    istio_init_template_path: "{{tmp_dir}}/istio-init-generated.yaml"

- name: Generate template istio init
  shell: "helm template {{istio_installation_path}}/helm/istio-init --namespace {{istio_namespace}} -f {{role_path}}/templates/{{istio_version}}/values/default.yml > {{istio_init_template_path}}"
  ignore_errors: false

- name: Deploy istio init
  shell: "{{ cmd_path }} -n {{istio_namespace}} apply -f {{istio_init_template_path}}"
  ignore_errors: true # TODO: Should not ignore

- include_tasks: ../../common/tasks/verify_jobs.yml
  vars:
    namespace: "{{istio_namespace}}"
    condition: '<'
    condition_expected_value: 3 # TODO: This may vary based on version