apiVersion: kops/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: 2017-05-04T23:21:47Z
  name: {{.environment}}.{{.name}}.{{.dnsZone}}
spec:
  api:
#    loadBalancer:
#      type: Public
#      additionalSecurityGroups:
#      - sg-d8083091
  authorization:
    alwaysAllow: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://{{.s3StateBucket}}/{{.environment}}.{{.name}}.{{.dnsZone}}
  etcdClusters:
  - etcdMembers:
    - instanceGroup: master-{{.awsRegion}}a
      name: a
    - instanceGroup: master-{{.awsRegion}}b
      name: b
    - instanceGroup: master-{{.awsRegion}}c
      name: c
    name: main
  - etcdMembers:
    - instanceGroup: master-{{.awsRegion}}a
      name: a
    - instanceGroup: master-{{.awsRegion}}b
      name: b
    - instanceGroup: master-{{.awsRegion}}c
      name: c
    name: events
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.6.6
  masterPublicName: api.{{.environment}}.{{.name}}.{{.dnsZone}}
  networkCIDR: 172.31.0.0/16
  networkID: {{.vpcId}}
  networking:
    weave: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.31.32.0/20
    id: subnet-1ef51944
    name: {{.awsRegion}}a
    type: Public
    zone: {{.awsRegion}}a
  - cidr: 172.31.0.0/20
    id: subnet-77113512
    name: {{.awsRegion}}b
    type: Public
    zone: {{.awsRegion}}b
  - cidr: 172.31.64.0/20
    name: {{.awsRegion}}c
    id: subnet-7f20d653
    type: Public
    zone: {{.awsRegion}}c
  topology:
#    bastion:
#      bastionPublicName: bastion.{{.environment}}.{{.name}}.{{.dnsZone}}
    dns:
      type: Public
    masters: public
    nodes: public

#---
#
#apiVersion: kops/v1alpha2
#kind: InstanceGroup
#metadata:
#  creationTimestamp: 2017-05-04T23:21:48Z
#  labels:
#    kops.k8s.io/cluster: {{.environment}}.{{.name}}.{{.dnsZone}}
#  name: bastions
#spec:
#  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
#  machineType: {{.bastionInstanceType}}
#  maxSize: 1
#  minSize: 1
#  role: Bastion
#  subnets:
#  - us-east-1a
#  - us-east-1b
#  - us-east-1c

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-04T23:21:47Z
  labels:
    kops.k8s.io/cluster: {{.environment}}.{{.name}}.{{.dnsZone}}
  name: master-{{.awsRegion}}a
spec:
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: {{.masterInstanceType}}
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 75
  rootVolumeType: gp2
  subnets:
  - {{.awsRegion}}a
  additionalSecurityGroups:
  - sg-d8083091


---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-04T23:21:47Z
  labels:
    kops.k8s.io/cluster: {{.environment}}.{{.name}}.{{.dnsZone}}
  name: master-{{.awsRegion}}b
spec:
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: {{.masterInstanceType}}
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 75
  rootVolumeType: gp2
  subnets:
  - {{.awsRegion}}b
  additionalSecurityGroups:
  - sg-d8083091

---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-04T23:21:47Z
  labels:
    kops.k8s.io/cluster: {{.environment}}.{{.name}}.{{.dnsZone}}
  name: master-{{.awsRegion}}c
spec:
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: {{.masterInstanceType}}
  maxSize: 1
  minSize: 1
  role: Master
  rootVolumeSize: 75
  rootVolumeType: gp2
  subnets:
  - {{.awsRegion}}c
  additionalSecurityGroups:
  - sg-d8083091


---

apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: 2017-05-04T23:21:48Z
  labels:
    kops.k8s.io/cluster: {{.environment}}.{{.name}}.{{.dnsZone}}
  name: nodes
spec:
  image: kope.io/k8s-1.6-debian-jessie-amd64-hvm-ebs-2017-05-02
  machineType: {{.nodeInstanceType}}
  maxSize: 3
  minSize: 3
  rootVolumeSize: 75
  rootVolumeType: gp2
  role: Node
  subnets:
  - {{.awsRegion}}a
  - {{.awsRegion}}b
  - {{.awsRegion}}c
  additionalSecurityGroups:
  - sg-d8083091