- name: Create Kiali Secret
  shell: "echo \"{{ secret | to_yaml }}\" | {{cmd_path}} create -f - "
  ignore_errors: true

- include_tasks: create_certificates.yml
  loop:
     - grafana
     - kiali
     - prometheus
     - istio
     - jaeger

