
- command: "{{ cmd_path }} -n {{istio_namespace}} get pod -l app={{item}} -o custom-columns=STATUS:.status.phase"
  register: results
  retries: 20
  delay: 5
  until: results.stdout | regex_findall("^Running", multiline=True, ignorecase=True) | length >= 1
  
- name: istio_pilot_resultsresults
  debug:
    msg: "{{ results }}"