---
- include_tasks: set_appropriate_cmd_path.yml
  when: cmd_path is not defined

- name: Extract server version
  shell: |
    {{ cmd_path }} version | sed -En "{{'s/kubernetes.*v([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+).*/\1/p' if cluster_flavour == 'ocp' else 's/Server Version.*GitVersion.*v([[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+).*/\1/p'}}" | tail -1
  register: vo

- name: Assert k8s version
  assert:
    that:
      - "vo.stdout is version_compare(minimum_cluster_version,'>=')"
    msg: "Cluster version must be at least {{ minimum_cluster_version }}"

# CREATE NS
- include_tasks: safely_create_namespace.yml
  vars:
    ns_name: 'istio-system'

# CREATE REQUIRED SECRETS
- include_tasks: create_secrets.yml

# INSTALL ISTIO-INIT
- include_tasks: deploy_istio_init.yml

# INSTALL ISTIO
- include_tasks: deploy_istio.yml


# DEPLOY POLICIES
- include_tasks: deploy_policies.yml

# DEPLOY GATEWAYS
- include_tasks: deploy_gateways.yml