---
- include_tasks: set_appropriate_cmd_path.yml
  when: cmd_path is not defined

- include_tasks: requirements.yml

- name: Creates Outputs directory
  file:
    path: "{{role_path}}/.generated"
    state: directory
    force: true
  when:
  - action == "deploy"

- name: Tmp directory for execution
  set_fact:
    tmp_dir: "{{role_path}}/.generated"

# CREATE NS
- include_tasks: safely_create_namespace.yml
  vars:
    ns_name: 'istio-system'
  when:
  - action == "deploy"

# CREATE REQUIRED SECRETS
- include_tasks: create_secrets.yml
  when:
  - action == "deploy"

# INSTALL ISTIO-INIT
- include_tasks: deploy_istio_init.yml
  when:
  - action == "deploy"

# INSTALL ISTIO
- include_tasks: deploy_istio.yml
  when:
  - action == "deploy"

# DEPLOY POLICIES
- include_tasks: deploy_policies.yml
  when:
  - action == "deploy"

# DEPLOY GATEWAYS
- include_tasks: deploy_gateways.yml
  when:
  - action == "deploy"

# DELETE ISTIO-INIT
- include_tasks: delete_istio_init.yml
  when:
  - action == "delete"

# DELETE ISTIO
- include_tasks: delete_istio.yml
  when:
  - action == "delete"