apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "app"
spec:
  host: "*.app.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE