- name: Delete Knative Monitoring
  shell: |
    kubectl delete -f https://github.com/knative/serving/releases/download/v{{monitoring.version}}/monitoring.yaml
  register: knative_monitoring_install
  ignore_errors: true
  
- name: Print Knative Monitoring Delete Results
  debug:
    msg: "{{ knative_monitoring_install }}"
