# apiVersion: serving.knative.dev/v1alpha1
# kind: Configuration
# metadata:
#   name: blue-green-demo
#   namespace: applications
# spec:
#   template:
#     metadata:
#       labels:
#         knative.dev/type: container
#     spec:
#       containers:
#         - image: docker.io/manny87/knative-helloworld:1.0 # The URL to the sample app docker image
#           env:
#             - name: TARGET
#               value: "blue"

---
apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: blue-green-demo
  namespace: applications
spec:
  template:
    metadata:
      labels:
        knative.dev/type: container
    spec:
      containers:
        - image: docker.io/manny87/knative-helloworld:latest # The URL to the sample app docker image
          env:
            - name: TARGET
              value: "green"