apiVersion: v1
kind: Namespace
metadata:
  name: applications
---
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "applications"
spec:
  host: "*.applications.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE