- hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
  - include_tasks: "{{playbook_dir}}/tasks/antlet_get.yaml"
  
  - include_tasks: "{{playbook_dir}}/tasks/antlet_stop.yaml"
    vars:
      antlet_name: "{{ item.dname }}" 
    with_items:  "{{ registered_antlets }}"
    when: '"k8s1-" in item.dname'

  - include_tasks: "{{playbook_dir}}/tasks/antlet_wait_state.yaml"
    vars:
      antlet_to_wait_for: "{{ item.dname }}" 
      state_name: "Stopped"
    with_items:  "{{ registered_antlets }}"
    when: '"k8s1-" in item.dname'
  
  - include_tasks: "{{playbook_dir}}/tasks/antlet_start.yaml"
    vars:
      antlet_name: "{{ item.dname }}" 
    with_items:  "{{ registered_antlets }}"
    when: '"k8s1-" in item.dname'

  - include_tasks: "{{playbook_dir}}/tasks/antlet_wait_state.yaml"
    vars:
      antlet_to_wait_for: "{{ item.dname }}" 
      state_name: "Running"
    with_items:  "{{ registered_antlets }}"
    when: '"k8s1-" in item.dname'