- hosts: k8s1-master
  vars_files:
    - vars.yaml
  tasks:
  # SET UP ROUTES TO POD NETWORK
  # TODO: MAKE DYNAMIC
  - name: Current Routes
    command: ip route
    register: current_routes
  
  - name: IP Route(s)
    command: ip route add 10.244.0.0/24 via 10.10.1.20
    when: '"10.244.0.0/24 via 10.10.1.20" not in current_routes.stdout'

  - name: IP Route(s)
    command: ip route add 10.244.1.0/24 via 10.10.1.21
    when: '"10.244.1.0/24 via 10.10.1.21" not in current_routes.stdout'

  - name: IP Route(s)
    command: ip route add 10.244.2.0/24 via 10.10.1.22
    when: '"10.244.2.0/24 via 10.10.1.22" not in current_routes.stdout'