apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: knative-2-py
  namespace: py2-apps
  # labels:
  #   serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
      - image: docker.io/manny87/knative-py:1.2
        ports:
          - name: http1
            containerPort: 8080
            protocol: TCP
---