
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knative-consumer
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: knative-consumer
  template:
    metadata:
      labels: *labels
    spec:
      containers:
        - name: knative-consumer
          image: docker.io/manny87/knative-consumer-producer:1.10
          command: ["/app/app"]
          args: ["-mode=consumer"]
---
# Service that exposes helloworld-go app.
# This will be the subscriber for the Trigger
  kind: Service
  apiVersion: v1
  metadata:
    name: knative-consumer
  spec:
    selector:
      app: knative-consumer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---