- name: Install yum packages
  yum:
    name:
    - haproxy
    - yum-utils
    - wget
    state: present

- name: Creates HAProxy dir
  file:
    path: "/etct/haproxy"
    state: directory

- name: Push HAProxy config
  template:
    src: "{{ playbook_dir }}/templates/haproxy/haproxy.cfg.j2"
    dest: "/etc/haproxy/haproxy.cfg"

- name: Start/Enable Data Plane component services
  systemd:
    state: started
    daemon_reload: yes
    name: "{{ item }}"
    enabled: yes
  loop:
  - haproxy

- name: Restart Services
  systemd:
    state: restarted
    daemon_reload: yes
    name: "{{item}}"
  loop:
  - haproxy