- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: yum-makecache
  command: yum makecache


- name: Install yum packages
  yum:
    name:
    - wget
    - epel-release
    - policycoreutils-python
    - yum-utils
    - epel-release
    - device-mapper-persistent-data
    - lvm2
    - nmap-ncat.x86_64
    - traceroute
    # - libselinux-python
    # - firewalld
    state: present