apiVersion: v1
kind: Namespace
metadata:
  name: "{{namespace}}"
  labels:
    knative-eventing-injection: enabled
---
# Required when MTLS is enabled...
# TODO: Identify a permanent solution, if it exists...
apiVersion: "networking.istio.io/v1alpha3"
kind: "DestinationRule"
metadata:
  name: "default"
  namespace: "{{namespace}}"
spec:
  host: "*.{{namespace}}.svc.cluster.local"
  trafficPolicy:
    tls:
      mode: DISABLE